BOOKMOTION/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('elib.urls', namespace='elib')),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('admin/', admin.site.urls),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

auth_app/urls.py
from django.urls import path
from auth_app import views

app_name = 'auth_app'

urlpatterns = [
    path('', views.home, name='home'),
    # student
    path('register-student/', views.register_student, name='register-student'),
    path('register-staff/', views.register_staff, name='register-staff'),
    path('login-student/', views.login_student, name='login-student'),
    path('logout/', views.logout_user, name='logout'),

    # staff
    path('login-staff/', views.login_staff, name='login-staff'),
]

elib/urls.py
from django.urls import path
from elib import views

app_name = 'elib'

urlpatterns = [
    path('', views.home, name='home-page'),
    path('details/<str:slug>/', views.details, name='details'),
    path('borrow/<str:slug>/', views.borrow, name='borrow'),
    path('borrowed/', views.borrowed, name='borrowed'),
    path('upload/', views.upload, name='upload'),
]

templates/Layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BOOK MOTION</title>
  <link rel="shortcut icon" type="x-icon" href="/static/css/images/favcon2.png">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="{% static '/css/style.css' %}"> -->
</head>



<style>
    * {
      box-sizing: border-box;
      padding: 0;
      margin: 0;
    }
    .grid-container{
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 1rem;
      padding: 2rem 1rem;
      overflow: hidden;
    }
    img {
        width: 100%;
        height: 100%;
    }
  </style>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">ELIB</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto p-3">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'elib:home-page' %}">HOME <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'elib:borrowed' %}">BORROWED BOOKS</a>
          {% endif %}
        </li>

        {% if request.user.is_staff %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'elib:upload' %}">UPLOAD BOOKS</a>
          </li>
        {% endif %}
        <li class="nav-item">
          {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'auth_app:logout' %}">LOG OUT</a>
          {% else %}
            <a class="nav-link" href="{% url 'auth_app:home' %}">LOG IN</a>
          {% endif %}
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'elib:home-page' %}">
        <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search By Title</button>
      </form>
    </div>
  </nav>
    {% block content %}

    {% endblock content %}

</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BOOK MOTION</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="{% static '/css/style.css' %}"> -->
</head>



<style>
    * {
      box-sizing: border-box;
      padding: 0;
      margin: 0;
    }
    .grid-container{
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 1rem;
      padding: 2rem 1rem;
      overflow: hidden;
    }
    img {
        width: 100%;
        height: 100%;
    }
  
  </style>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">ELIB</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" >
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto p-3">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'elib:home-page' %}" color ="blue">HOME <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'elib:borrowed' %}">BORROWED BOOKS</a>
          {% endif %}
        </li>
        
        {% if request.user.is_staff %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'elib:upload' %}">UPLOAD BOOKS</a>
          </li>
        {% endif %}
        <li class="nav-item">
          {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'auth_app:logout' %}">LOG OUT</a>
          {% else %}
            <a class="nav-link" href="{% url 'auth_app:home' %}">LOG IN</a>
          {% endif %}
        </li> 
      </ul>
      <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'elib:home-page' %}">
        <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search By Title</button>
      </form>
    </div>
  </nav>
    {% block content %}

    {% endblock content %}

</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>